[vcpkg baseline][qt5-base] Add option disable feature gssapi to fix ci baseline (#38670)
Fixes regression:
https://dev.azure.com/vcpkg/public/_build/results?buildId=102737&view=results
````
REGRESSION: lunarg-vulkantools:x64-linux failed with BUILD_FAILED
REGRESSION: qt5-serialbus:x64-linux failed with BUILD_FAILED
````
Error:
````
/usr/bin/ld: /mnt/vcpkg-ci/b/krb5/x64-linux-dbg/lib/gssapi/krb5/../../.././../src/krb5-1-8a38cd677f.clean/src/lib/gssapi/krb5/export_name.c:61: undefined reference to `krb5_free_context'
````
Add option _--gssapi=no_ to disable use feature gssapi
Remove
````
lunarg-vulkantools:x64-linux=fail
qt5-serialbus:x64-linux=fail 
```` 
from ci.baseline.txt
- [x] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by
this new version.~~
- [ ] ~~Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the
port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

---------

Co-authored-by: Jon <v-zhli17@microsoft.com>