[qtbase] Fix "There should be no absolute paths" (#37986)
Problem occurs on x64-linux-dynamic.

```
warning: There should be no absolute paths, such as the following, in an installed package:
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic
  /home/XXX/prog/vcpkg/installed
  /home/XXX/prog/vcpkg/buildtrees/qtbase
  /home/XXX/prog/vcpkg/downloads
Absolute paths were found in the following files:
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Concurrent.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Core.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6DBus.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Gui.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Network.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6OpenGL.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6OpenGLWidgets.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Platform.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6PrintSupport.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Sql.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Test.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Widgets.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/debug/lib/pkgconfig/Qt6Xml.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Concurrent.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Core.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6DBus.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Gui.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Network.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6OpenGL.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6OpenGLWidgets.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Platform.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6PrintSupport.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Sql.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Test.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Widgets.pc
  /home/XXX/prog/vcpkg/packages/qtbase_x64-linux-dynamic/lib/pkgconfig/Qt6Xml.pc
error: Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: /home/XXX/prog/vcpkg/ports/qtbase/portfile.cmake
```

- [ ] Changes comply with the [maintainer
guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by
this new version.~~
- [ ] ~~Any fixed [CI
baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)
entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the
port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version
--all` and committing the result.
- [X] Only one version is added to each modified port's versions file.